# Site Settings
#===============================================================================
title: Lisa Eisner Jewelry
email: info@lisaeisnerjewelry.com
description: "Jewelry created by artist and photographer Lisa Eisner, Los Angeles CA."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
#===============================================================================
markdown: redcarpet
redcarpet: 
  extensions: ["smart", "strikethrough"]

highlighter: pygments
exclude: [Gemfile, Gemfile.lock, readme.md]

# Permalinks
#===============================================================================
permalink: none

# Assets
#===============================================================================
sass:
  sass_dir: assets/styles/_scss  # default is _sass
  style: compressed # set to compressed for production


# Prose Settings
#===============================================================================
prose:
  ignore: ['.gitignore', '_config.yml', 'test.html', 'Gemfile', 'Gemfile.lock', 'assets', '_includes', '_layouts', '_data']



