# Site settings
title: Lisa Eisner Studio
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "http://ericgardner.info/sandbox/lisaeisner"
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll
exclude: ['node_modules', '.sass-cache', 'gruntfile.js', 'package.json', '.gitignore', 'js/libs', 'css/base', 'css/bourbon', 'css/neat', '*.scss']

# Build settings
markdown: kramdown
permalink: pretty
sass:
    style: compressed